name: lasertram-db
channels:
  - conda-forge
dependencies:
  - python=3.12
  - dash=3.0.4
  - dash-bootstrap-components
  - ca-certificates
  - openssl
  - pip
  - plotly
  - pip:
    - lasertram==1.0.2
